all:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: ./id_rsa
    ansible_python_interpreter: /opt/docker_venv/bin/python
  children:
    prod:
      hosts:
        kaci.bouaouli.takima.cloud
