- name: Run Application
  docker_container:
    name: my-api
    image: "kacibouaouli/tp-devops-simple-api:latest"
    state: started
    networks:
      - name: my_app_network
    ports:
      - "8080:8080"
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
    
