- name: Run Proxy
  docker_container:
    name: my_proxy
    image: "kacibouaouli/tp-devops-httpd:latest"
    state: started
    networks:
      - name: my_app_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
